version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - yarn-{{ checksum "yarn.lock" }}
        - yarn-
    - run: yarn install
    - run: yarn storybook:build
    - save_cache:
        paths:
        - node_modules
        key: yarn-{{ checksum "yarn.lock" }}
    - deploy:
        command: yarn storybook:deploy --token ${FIREBASE_TOKEN}
